package com.mycom.entity;

public class StorageFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_file.ID
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_file.FILE_NAME
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_file.STORAGE_SHARE
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    private String storageShare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_file.STORAGE_PARENT_DIR
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    private String storageParentDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_file.STORAGE_CHILD_DIR
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    private String storageChildDir;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_file.ID
     *
     * @return the value of storage_file.ID
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_file.ID
     *
     * @param id the value for storage_file.ID
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_file.FILE_NAME
     *
     * @return the value of storage_file.FILE_NAME
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_file.FILE_NAME
     *
     * @param fileName the value for storage_file.FILE_NAME
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_file.STORAGE_SHARE
     *
     * @return the value of storage_file.STORAGE_SHARE
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    public String getStorageShare() {
        return storageShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_file.STORAGE_SHARE
     *
     * @param storageShare the value for storage_file.STORAGE_SHARE
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    public void setStorageShare(String storageShare) {
        this.storageShare = storageShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_file.STORAGE_PARENT_DIR
     *
     * @return the value of storage_file.STORAGE_PARENT_DIR
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    public String getStorageParentDir() {
        return storageParentDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_file.STORAGE_PARENT_DIR
     *
     * @param storageParentDir the value for storage_file.STORAGE_PARENT_DIR
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    public void setStorageParentDir(String storageParentDir) {
        this.storageParentDir = storageParentDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_file.STORAGE_CHILD_DIR
     *
     * @return the value of storage_file.STORAGE_CHILD_DIR
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    public String getStorageChildDir() {
        return storageChildDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_file.STORAGE_CHILD_DIR
     *
     * @param storageChildDir the value for storage_file.STORAGE_CHILD_DIR
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    public void setStorageChildDir(String storageChildDir) {
        this.storageChildDir = storageChildDir;
    }
}