package com.mycom.dao;

import com.mycom.entity.StorageFile;
import com.mycom.entity.StorageFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StorageFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_file
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    long countByExample(StorageFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_file
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    int deleteByExample(StorageFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_file
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_file
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    int insert(StorageFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_file
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    int insertSelective(StorageFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_file
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    List<StorageFile> selectByExample(StorageFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_file
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    StorageFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_file
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") StorageFile record, @Param("example") StorageFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_file
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    int updateByExample(@Param("record") StorageFile record, @Param("example") StorageFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_file
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    int updateByPrimaryKeySelective(StorageFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_file
     *
     * @mbg.generated Tue Mar 13 10:15:32 CST 2018
     */
    int updateByPrimaryKey(StorageFile record);
}